version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: always
    ports:
      - "3306:3306"
    command: mysqld --sql_mode="" --character-set-server=utf8  --init-connect='SET NAMES UTF8;' --skip_name_resolve
    volumes:
      - 'mis_datos:/var/lib/mysql'

volumes:
  mis_datos:
